[package]
name = "prophetouw/cleanit"
version = "2.0.4"
registry = "https://github.com/ProphetOuw/CleanIt"
realm = "shared"
license = "MIT"
description = "A memory cleaning helper."
authors = ["ProphetOuw <ouwproduction@gmail.com>"]